### ISSUE TITLE
Versioneer with Travis CI

### ISSUE THREAD

**Issue by afonsoc12** [python-versioneer/python-versioneer#243]
Hello,
I have this repository that has a CI config to deploy to PyPI. I use versioneer.get_version() on setup.py (which works on CI) and I call ._version.get_versions()['default'] to display the version on runtime.

However, the version can't be computed on the released package.

From what I understand, Travis can get the version for setup.py because it does a shallow clone (I have read #114), but the released package does not have git information to compute the version.

My question is: what is the proper way to display the version on the released package, using versioneer? Is it possible to automatically write the version on a .txt or something?

Thanks!

**Comment by effigies** [comment]
What is your build process? When you build an sdist or wheel, the `_version.py` should be replaced by a stub with the versions determined at build time so that there is no need to access git.

**Comment by afonsoc12** [comment]
Thank you for your reply.
 My .travis.yml has the following:
```yaml
deploy:
  - provider: pypi
    edge: true
    server: https://test.pypi.org/legacy/
    remove_build_dir: false
    distributions: "sdist bdist_wheel"
    username: "__token__"
    password:
      secure: "password"
    on:
      branch: master
      tags: true
```

I build both sdist and bdist_wheel, howerver, the deployed file does not have the version. Also, I just tried to build it locally and the sdist (tar.gz) has the same _version.py as the one on git
