### ISSUE TITLE
Support for hatchling and pdm

### ISSUE THREAD

**Issue by kiyoon** [python-versioneer/python-versioneer#401]
Nowadays, it is becoming popular to use a modern build system. Versioneer is my favourite of all versioning tools I've used, but unfortunately it is limited to setuptools, which is limiting me to move onto different build systems. I tried versioneer with `hatch` as follows:

```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "code"
path = "src/my_project/_version.py"
expression = "get_versions()['version']"
```

This was very straightforward so far. But the real problem is that versioneer doesn't provide a hook API to use for building sdist etc. and the `_version.py` needs to be replaced to a file with a constant when building!

This should be very easy to do with hooks:

https://hatch.pypa.io/latest/plugins/build-hook/reference/#hatchling.builders.hooks.plugin.interface.BuildHookInterface--hookspy

I'm not so sure about the `cmdclass` problem. It seems for me that if we can implement the hook it should be no problem at all.

I appreciate your work on this project!

**Comment by kiyoon** [comment]
```toml
[tool.hatch.build.hooks.custom]
path = "hatch_build.py"

[tool.hatch.build.force-include]
"build_outputs/_version.py" = "src/ml_project/_version.py"
```

If the hook creates the _version.py file, you can replace the file like this.
